
adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
plural_noun = input("Enter a Plural Noun: ")
someone_in_house = input("Enter a Family Members Name: ")
adjective2 = input("Enter another Adjective: ")
article_of_clothing = input("Enter an Article of Clothing: ")
noun2 = input("Enter another Noun: ")
a_city = input("Enter a City: ")
plural_noun2 = input("Enter another Plural Noun: ")
adjective3 = input("Enter another Adjective: ")
part_of_the_body = input("Enter a Part of the Body: ")
letter_of_the_alphabet = input("Enter a Letter of the Alphabet: ")
celebrity = input("Enter a Celebrity: ")
plural_noun3 = input("Enter another Plural Noun: ")
adjective4 = input("Enter another Adjective: ")
a_place = input("Enter a place: ")
part_of_the_body2 = input("Enter another Part of the Body: ")
adjective5 = input("Enter another Adjective: ")
adjective6 = input("Enter another Adjective: ")
verb = input("Enter a Verb: ")
plural_noun4 = input("Enter another Plural Noun: ")
number = input("Enter a Number: ")


print("There are many " + adjective)
print("ways to choose a/an " + noun + " to read.")
print("First you can ask for recommendations from your friends and " + plural_noun + ".")
print("Just don't ask Aunt " + someone_in_house + ",")
print("she only reads " + adjective2)
print("books with " + article_of_clothing + "-ripping goddesses on the cover.")
print("If your friends and family are no help, try checking out the " + noun2)
print("Review in The " + a_city + " Times.")
print("If the " + plural_noun2)
print("featured there are too " + adjective3)
print("for your taste, try something a little more low-" + part_of_the_body + ",")
print("like " + letter_of_the_alphabet + ":")
print("The " + celebrity + " Magazine,")
print("or " + plural_noun3 + " Magazine.")
print("You could also choose a book the " + adjective4 + "-fashioned way.")
print("Head to your local library or " + a_place + " and browse the shelves until")
print("something catches your " + part_of_the_body2 + ".")
print("Or, you could save yourself a whole lot of " + adjective4 + " trouble and log on")
print("to www.bookish.com, the " + adjective5 + " new website")
print("to " + verb + " for books!")
print("With all the time you'll save not having to search for " + plural_noun4 + " you can")
print("read " + number + " more books!")